.github/workflows/appsignals-e2e-eks-test.yml
.github/workflows/release-build.yml

Run E2E test on demand for when changes are made to the enablement script.
Changes:
- Create new release testing workflow
- Create E2E test workflow for EKS as in ADOT repo
- Changes made to this to pull the testing resources directly from ADOT (by pulling ADOT repo altogether)
- Removed steps specific to ADOT (removed release testing check for ADOT, removed failure metric emission)
- Calling API ahead of validation as an improvement (same change is planned for ADOT repo)
Note: This workflow does not test on PR because the AWS credential configuration using OIDC does not work under the context of a PR build (permissions are automatically set to `read` instead of `write` for `id-token`) - [example of the operation hanging](https://github.com/aws-observability/application-signals-demo/action …

E2E Testing: Create release testing workflow

---

scripts/eks/appsignals/create-canaries.sh

*Issue*
The creation of canaries will soon fail due to the new Lambda release.
Create canaries with runtime version v6.2.

Update canary runtime version to 6.2

---

.github/workflows/appsignals-e2e-eks-test.yml

Testing resources for E2E Testing has been moved to https://github.com/aws-observability/aws-application-signals-test-framework, need to update e2e testing workflow to retrieve from that repo. 
Test Run: https://github.com/aws-observability/application-signals-demo/actions/runs/8100756207

Retrieve E2E testing resources from application framework repo

---

scripts/eks/appsignals/enable-app-signals.sh

The EKS add-on on the enable-app-signals.sh script is still using the old v1.2.0 version
Removed argument in the script that specifies the version, thereby using the latest one. 
Test run: https://github.com/aws-observability/application-signals-demo/actions/runs/8176925726/job/22357422956#step:13:50

Update enable-app-signal script to use the latest addon

---

scripts/eks/appsignals/enable-app-signals.sh

Update add-on version as new CW add-on with python support released.
Release testing workflow run to make sure the change is secure: https://github.com/aws-observability/application-signals-demo/actions/runs/8526578457/job/23356139901

Update add-on version.

---

scripts/eks/appsignals/deploy-sample-app.sh
scripts/eks/appsignals/one-step/cleanup.sh

- Updated cleanup script to avoid deadlock when deleting persistent volume.
- Tested the script multiple times and verified that it works as expected.

Updated cleanup script to avoid deadlock when deleting persistent volume.

---

scripts/eks/appsignals/clean-app-signals.sh

The log group used to store EMF logs has been changed to `/aws/application-signals/data`. Currently the clean-app-signals.sh script is failing due to this mismatch. 
Update the log group deletion command
Test:
Ran latest `enable-app-signals.sh` in EKS cluster, generated telemetry, then ran `clean-app-signal.sh`. No errors during the process

Update Log Group to /aws/application-signals/data

---

README.md
scripts/ec2/appsignals/setup-ec2-demo.sh
scripts/eks/appsignals/deploy-sample-app.sh
scripts/k8s/appsignals/setup-k8s-demo.sh
spring-petclinic-api-gateway/src/main/java/org/springframework/samples/petclinic/api/application/CustomersServiceClient.java
spring-petclinic-api-gateway/src/main/java/org/springframework/samples/petclinic/api/boundary/web/ApiController.java
spring-petclinic-customers-service/pom.xml
spring-petclinic-customers-service/src/main/java/org/springframework/samples/petclinic/customers/aws/BedrockAgentV1Service.java
spring-petclinic-customers-service/src/main/java/org/springframework/samples/petclinic/customers/aws/BedrockAgentV2Service.java
spring-petclinic-customers-service/src/main/java/org/springframework/samples/petclinic/customers/aws/BedrockRuntimeV1Service.java
spring-petclinic-customers-service/src/main/java/org/springframework/samples/petclinic/customers/aws/BedrockRuntimeV2Service.java
spring-petclinic-customers-service/src/main/java/org/springframework/samples/petclinic/customers/aws/BedrockV1Service.java
spring-petclinic-customers-service/src/main/java/org/springframework/samples/petclinic/customers/aws/BedrockV2Service.java
spring-petclinic-customers-service/src/main/java/org/springframework/samples/petclinic/customers/web/PetResource.java
spring-petclinic-customers-service/src/test/java/org/springframework/samples/petclinic/customers/web/PetResourceTest.java
terraform/eks/main.tf
traffic-generator/index.js

Add Bedrock & Bedrock runtime API call examples for feel and trial purpose. The major changes are
1. Added a new `customer/diagnose/owners/*` API in gateway service for Bedrock api invokes'
2. Extended customer service to
* call BedrockAgent via AWS SDK v1 and v2
* call Bedrock runtime via AWS SDK v1 on Titian model and v2 on Claude model
* call bedrock via AWS SDK v1 and v2 for Guardrails APIs

Bedrock genai demo

---

README.md

#48 
In order to use CloudWatch Application Signals, the Cloudwatch Observability Addon version requires v1.7.0-eksbuild.1, but it's v1.5.1-eksbuild.1 in the readme.
Therefore, I have changed to the current latest version.

Upgrade Cloudwatch Observability add-on version

---

scripts/ecs/appsignals/sample-app/task-definitions/spring-petclinic-api-gateway.json
scripts/ecs/appsignals/sample-app/task-definitions/spring-petclinic-billing-service.json
scripts/ecs/appsignals/sample-app/task-definitions/spring-petclinic-customers-service.json
scripts/ecs/appsignals/sample-app/task-definitions/spring-petclinic-insurance-service.json
scripts/ecs/appsignals/sample-app/task-definitions/spring-petclinic-vets-service.json
scripts/ecs/appsignals/sample-app/task-definitions/spring-petclinic-visits-service.json
scripts/ecs/appsignals/sample-app/task-definitions/traffic-generator.json
scripts/ecs/appsignals/setup-ecs-demo.sh

This PR is a fix on PR: https://github.com/aws-observability/application-signals-demo/pull/59, to consolidate ECS tasks to share the same IAM roles.

Consolidate ECS tasks to share the same IAM roles.

---

scripts/eks/appsignals/sample-app/api-gateway-deployment.yaml
scripts/k8s/appsignals/sample-app/api-gateway-deployment.yaml

We found a strange issue with the pet-clinic frontend microservice: it can't forward traffic to other microservice because the load balancer used by spring application failed to work with the discovery server. This issue seems to started on Nov 25. We don't know exactly the root cause. (If you have a running sample app in EKS, you will observe this issue by simply restarting the pods. In this case, you have no external changes but the issue will show up. We have done pod restarting multiple times previously but never saw this issue. So it's really mysterious what triggered it) 
To workaround this issue, we use a different spring profile and setting the config server and discovery server as environmental variables in the deployment yaml …

use different spring profile for api gateway

---

cdk/ec2/ec2-cdk.sh
cdk/ecs/ecs-cdk.sh
cdk/ecs/lib/stacks/databaseStack.ts
cdk/eks/eks-cdk.sh

CDK deployment bash script indicates success despite failing. Also, there is a conflict between EC2 and ECS CDK due to sharing the same db credential name
- Add exit 1 to all failed cdk deployment. 
- Update ECS db credential secret name

Add exit 1 for failed cdk and also update ECS DB credential name

---

cdk/eks/bin/eks.ts
cdk/eks/lib/manifests/sample-app/billing-service-deployment.yaml
cdk/eks/lib/manifests/sample-app/insurance-service-deployment.yaml
cdk/eks/lib/stacks/eks-stack.ts
cdk/eks/lib/stacks/iam-stack.ts
cdk/eks/lib/stacks/network-stack.ts
cdk/eks/lib/stacks/rds-stack.ts
cdk/eks/lib/utils/utils.ts
cdk/eks/package-lock.json

Replicating the changes in this [PR](https://github.com/aws-observability/application-signals-demo/pull/85) to cdk 
Verified that in service for `billing-service-python` and `insurance-service-python`, there is a new service operation and `postgresql` shows up in the dependencies

Add rds to eks cdk

---

scripts/eks/appsignals/setup-eks-demo.sh

The script is pointing to ecs rather than EKS. 
Also updating the permission of the file with `chmod +x` so that it's executable

Fix typo in setup-eks-demo.sh

---

cdk/eks/lib/stacks/slo-stack.ts

Fix a typo on operationName config and remove lambda SLO for now

Fix a typo on operationName config and remove lambda SLO for now

---

cdk/eks/lib/stacks/rds-stack.ts
cdk/eks/package.json

https://github.com/aws/aws-cdk/issues/32775
Fix RDS import issue and solve divergent aws-cdk and aws-cdk-lib version risk, which means, aws-cdk version will start from 2.1000 now and will no longer same as aws-cdk-lib version (example: 2.179/2.180)

Fix RDS import issue and solve divergent aws-cdk and aws-cdk-lib version risk

---

data_test/Readme.md
data_test/deploy/create_composite_alarms.py
data_test/deploy/create_test_cases_alarms.py
data_test/deploy/deploy_lambda.sh
data_test/deploy/remove_alarms.sh
data_test/deploy/remove_lambda.sh
data_test/lambda/lambda_function.py
data_test/lambda/logs_tester.py
data_test/lambda/metrics_tester.py
data_test/lambda/traces_tester.py
data_test/run_logs_tests.py
data_test/run_metrics_tests.py
data_test/run_trace_tests.py
data_test/test_cases/logs_test_cases.json
data_test/test_cases/metrics_test_cases.json
data_test/test_cases/traces_test_cases.json

Add a data verification test for APM Demo app

Add APM Demo Data Test

---

cdk/eks/eks-cdk.sh
cdk/eks/lib/manifests/traffic-generator/traffic-generator.yaml
cdk/eks/lib/stacks/eks-stack.ts
pet_clinic_billing_service/Dockerfile
pet_clinic_billing_service/requirements.txt
scripts/eks/appsignals/setup-eks-demo.sh

This commit includes multiple fixes to improve the stability and functionality
of the PetClinic microservices demo:
1. Fix traffic generator deployment by using private ECR repository image
instead of public one to ensure consistent image availability
2. Fix otel-collector service account permissions by properly configuring IAM
trust relationships for both service accounts in the EKS cluster
3. Fix billing-service-python crashes by adding missing OpenTelemetry API
dependency in both Dockerfile and requirements.txt
4. Enhance EKS deployment scripts with option to preserve stacks on failure
- Added --destroy-on-fail parameter to setup-eks-demo.sh
- Improved eks-cdk.sh to conditionally destroy stacks when deployment fails
By submitting this …

 fix multiple bugs

---

README.md
cdk/eks/lib/manifests/sample-app/billing-service-deployment.yaml

* Change the health check setting to use a different url path (`/health`). The previous path `/billings` is pretty heavy and has a high latency which will cause the pod to restart continuously due to health check failure
* Add instruction on how to access the EKS cluster

Fix health check and update doc

---

README.md
lambda-petclinic/cdk/lib/lambda-version-resource.ts
lambda-petclinic/cdk/tsconfig.json

Fix the image build issue due to permissions: 
```
ValidationError: Failed to bundle asset LambdaPetClinicStack/GetAppointmentVersioning/VersionHandler/Code/Stage, bundle output is located at
/local/home/pinxiang/test-slo/application-signals-demo/lambda-petclinic/cdk/cdk.out/asset.64f06d48a4bd71ee4b9d3d88aa28f6289151032ee882cb15165894818dec02be-building: ExecutionError: docker exited with
status 243
--> Command: docker run --rm -u "11896572:100" -v "/local/home/pinxiang/test-slo/application-signals-demo/lambda-petclinic/cdk/src/lambda-version-handler:/asset-input:delegated" -v
"/local/home/pinxiang/test-slo/application-signals-demo/lambda-petclinic/cdk/cdk.out/asset.64f06d48a4bd71ee4b9d3d88aa28f6289151032ee882cb15165894818dec02be-building: …
```

fix image build in CDK

---

ai-validator/cdk/Dockerfile

Pulling the base image without authenticating into docker may cause errors such as `toomanyrequests`
Pull the image from AWS public ECR rather than docker

Update Ai Validator Docker Base Image
