aws-observability/application-signals-demo

README.md
https://github.com/aws-observability/application-signals-demo/issues/4
Update the steps for ec2 demo to to ensure that jar files are compiled using the same Java version as their runtime environment.
=> update steps for ec2 demo

README.md
Update readme to warn the potential security risk for the publicly accessible application load balancer provided in the sample application. 
=> update readme to include some security info

README.md
=> Update README.md to include disclaimer

README.md
- Check java version to make sure the same java version is used for compilation and runtime.
- Use tmux to replace screen (tmux is more modern)
=> check java version and use tmux

README.md, scripts/eks/appsignals/create-slo.sh, scripts/eks/appsignals/one-step/cleanup.sh
Updated SLO creation script. Tested by deploying to petclinic sample app on my account and it worked as expected. 
=> Fixed SLO creation script

scripts/eks/appsignals/canaries/scripts/pc-create-owners.js, scripts/eks/appsignals/sample-app/customers-service-deployment.yaml
Changed replica count to 1 for customers service and updated canary.
=> Changed replica count to 1 for customers service and updated canary

push-ecr.sh, scripts/eks/appsignals/deploy-traffic-generator.sh, scripts/eks/appsignals/one-step/cleanup.sh, scripts/eks/appsignals/one-step/setup.sh, scripts/eks/appsignals/sample-app/traffic-generator.yaml, spring-petclinic-api-gateway/src/main/java/org/springframework/samples/petclinic/api/application/VisitsServiceClient.java, spring-petclinic-api-gateway/src/main/java/org/springframework/samples/petclinic/api/boundary/web/ApiController.java, spring-petclinic-api-gateway/src/main/resources/application.yml, spring-petclinic-customers-service/src/main/java/org/springframework/samples/petclinic/customers/CustomersServiceApplication.java, spring-petclinic-customers-service/src/main/java/org/springframework/samples/petclinic/customers/web/OwnerResource.java, spring-petclinic-visits-service/src/main/java/org/springframework/samples/petclinic/visits/VisitsServiceApplication.java, spring-petclinic-visits-service/src/main/java/org/springframework/samples/petclinic/visits/web/InvalidDateException.java, spring-petclinic-visits-service/src/main/java/org/springframework/samples/petclinic/visits/web/VisitResource.java, traffic-generator/Dockerfile, traffic-generator/index.js, traffic-generator/package.json
* add traffic generator
* clean up in-memory database periodically to avoid memory issue
* add date validation and error
=> Improve demo

README.md, pet_clinic_billing_service/ec2-setup.sh, pet_clinic_insurance_service/ec2-setup.sh, scripts/ec2/appsignals/cloudwatch-agent.json, scripts/ec2/appsignals/setup-ec2-demo.sh, scripts/ec2/appsignals/trust-policy.json
* Automate the setup for ec2 demo
* Added instrumentation for sample app
* Fixed some bugs
=> automate ec2 setup

README.md, push-public-ecr.sh, scripts/eks/appsignals/deploy-sample-app.sh, scripts/k8s/appsignals/allow-ecr-access.json, scripts/k8s/appsignals/deploy-sample-app.sh, scripts/k8s/appsignals/sample-app/db/db-pvc.yaml, scripts/k8s/appsignals/sample-app/db/storageclass.yaml, scripts/k8s/appsignals/setup-k8s-demo.sh, scripts/k8s/appsignals/traffic-generator.yaml, scripts/k8s/appsignals/trust-policy.json
=> set up k8s demo

pet_clinic_billing_service/ec2-setup.sh, pet_clinic_insurance_service/ec2-setup.sh, scripts/ec2/appsignals/setup-ec2-demo.sh, scripts/k8s/appsignals/setup-k8s-demo.sh
* add asg to ec2 setup
* remove `aws.hostedin.environment` otel attribute
* correct the repo link in k8s setup
=> add asg to ec2 setup

spring-petclinic-api-gateway/src/main/resources/application.yml, spring-petclinic-customers-service/src/main/java/org/springframework/samples/petclinic/customers/web/PetResource.java, spring-petclinic-customers-service/src/main/resources/application.yml, spring-petclinic-vets-service/src/main/resources/application.yml, spring-petclinic-visits-service/src/main/java/org/springframework/samples/petclinic/visits/aws/DdbService.java, spring-petclinic-visits-service/src/main/java/org/springframework/samples/petclinic/visits/web/VisitResource.java, spring-petclinic-visits-service/src/main/resources/application.yml
* Add config to inject trace context into logs
* Add logs for some operation for demo purposes
=> enable trace-log correlation (for EKS)

scripts/ec2/appsignals/setup-ec2-demo.sh, scripts/k8s/appsignals/deploy-sample-app.sh, scripts/k8s/appsignals/setup-k8s-demo.sh
* Change the kubelet config and restart kubelet to fix the certificate issue
=> fix kubeadmin certificate issue

spring-petclinic-api-gateway/pom.xml
Reverts aws-observability/application-signals-demo#44
=> Revert "Bump org.webjars:bootstrap from 3.3.7-1 to 5.0.0 in /spring-petclinic-api-gateway"

scripts/ec2/appsignals/cloudwatch-agent.json
Update configuration to match GA config.
=> Update configuration to match GA config

scripts/eks/appsignals/sample-app/nutrition-service-deployment.yaml, spring-petclinic-customers-service/src/main/resources/application.yml
Enable instrumentation in nutrition service and fix a typo.
=> Enable instrumentation in nutrition service and fix a typo.

scripts/eks/appsignals/sample-app/nutrition-service-deployment.yaml, scripts/k8s/appsignals/sample-app/nutrition-service-deployment.yaml
Enable nodejs instrumentation in EKS and K8s and correct a typo (of extra space)
=> enable nodejs instrumentation

spring-petclinic-customers-service/src/main/java/org/springframework/samples/petclinic/customers/aws/BedrockRuntimeV2Service.java
Fix Bedrock Claude model setup
=> Fix Bedrock Claude model setup

spring-petclinic-customers-service/src/main/java/org/springframework/samples/petclinic/customers/aws/BedrockAgentV1Service.java, spring-petclinic-customers-service/src/main/java/org/springframework/samples/petclinic/customers/aws/BedrockRuntimeV1Service.java, spring-petclinic-customers-service/src/main/java/org/springframework/samples/petclinic/customers/aws/BedrockV1Service.java
Make Bedrock & Bedrock client to set region from metadata API / Env var
=> Fix bedrock client region configuration

scripts/ecs/appsignals/setup-ecs-demo.sh
Add account replacement for ECS traffic generator.
=> Add account replacement for ECS traffic generator.

scripts/opentelemetry/appsignals_custom_otel_setup/custom-opentelemetry.yaml, scripts/opentelemetry/otel-custom-builder/Dockerfile, scripts/opentelemetry/otel-custom-builder/builder-config.yaml, scripts/opentelemetry/otel_simple_setup/opentelemetry.yaml
Add opentelemetry configuration examples for OTel collector and OTel SDK
=> Add opentelemetry configuration examples

scripts/eks/appsignals/install-otel-operator.sh, scripts/eks/appsignals/ocb/setup.sh
=> Add AmazonEKSWorkerNodePolicy for OCB ServiceAccount, rename script

cdk/eks/.gitignore, cdk/eks/lib/canaries/pc-add-visit/nodejs/node_modules/pc-add-visit.js, cdk/eks/lib/canaries/pc-create-owners/nodejs/node_modules/pc-create-owners.js, cdk/eks/lib/canaries/pc-visit-billings/nodejs/node_modules/pc-visit-billings.js, cdk/eks/lib/canaries/pc-visit-insurances/nodejs/node_modules/pc-visit-insurances.js, cdk/eks/lib/canaries/pc-visit-pet/nodejs/node_modules/pc-visit-pet.js, cdk/eks/lib/canaries/pc-visit-vet/nodejs/node_modules/pc-visit-vet.js, cdk/eks/lib/canaries/pet-clinic-traffic/nodejs/node_modules/pet-clinic-traffic.js
The canary folder was excluded in this [PR](https://github.com/aws-observability/application-signals-demo/pull/84) due to .gitignore rules. 
The canary script is copy paste from the `./scripts/eks/appsignals/canaries` folder
=> Add canary folder to eks cdk

README.md, cdk/ec2/package.json, cdk/ecs/package.json, cdk/eks/package.json
AWS CDK and Node.js versions are not clearly stated, which may cause CDK deployment failure. 
Specify Node.js version requirement in package.json
=> update node.js version requirement for CDK

cdk/eks/lib/stacks/slo-stack.ts, cdk/eks/package-lock.json
The application signals discovery is missing the 'iam:CreateServiceLinkedRole' permission. 
=> Update SLO Discovery Permission

cdk/eks/lib/stacks/eks-stack.ts
Due to the same federated principal being created in the `createVisitsServiceServiceAccount()` and `createOtelCollectorServiceAccount()`, it is creating an error `throw new Error(There is already a Construct with name '${childName}' in ${typeName}${name.length > 0 ? ' [' + name + ']' : ''});` during cdk deploy. 
Combining the above two methods into one new method called `createSampleAppRoleServiceAccount()`
=> Remove duplicate federated principal from eks cdk

cdk/eks/lib/stacks/eks-stack.ts, cdk/eks/lib/stacks/slo-stack.ts
Update CDK EKS SLOs, EKS Instance Config
=> Update CDK EKS SLOs, EKS Instance Config

README.md, cdk/eks/lib/stacks/rds-stack.ts, cdk/eks/package.json
Onboard to RDS Performance Insight Advanced, and upgrade aws-cdk-lib to 179.0 to support this new feature
=> Onboarding to Advanced Performance Insight and Upgrade CDK Version

cdk/eks/lib/stacks/my-application-stack.ts
N/A
The previous implementation of myApplication had the application name as "EksJavaDemoApp". This PR updates the name to "PetClinic_Application" and adds another sample myApplication to display multiple different applications.
Tested by deploying to sample account.
=> chore: update myApplication name to PetClinic_Application

cdk/eks/bin/eks.ts, cdk/eks/lib/canaries/pc-add-visit-error-rum/nodejs/node_modules/pc-add-visit-error-rum.js, cdk/eks/lib/canaries/pc-add-visit-rum/nodejs/node_modules/pc-add-visit-rum.js, cdk/eks/lib/canaries/pet-clinic-rum/nodejs/node_modules/pet-clinic-rum.js, cdk/eks/lib/manifests/sample-app/api-gateway-deployment.yaml, cdk/eks/lib/stacks/canary-stack.ts, cdk/eks/lib/stacks/eks-stack.ts, cdk/eks/lib/stacks/rum-stack.ts, cdk/eks/lib/utils/utils.ts, cdk/eks/package-lock.json, spring-petclinic-api-gateway/src/main/java/org/springframework/samples/petclinic/api/filter/RumConfigFilter.java, spring-petclinic-api-gateway/src/main/less/petclinic.less, spring-petclinic-api-gateway/src/main/resources/application.yml, spring-petclinic-api-gateway/src/main/resources/static/index.html, spring-petclinic-api-gateway/src/main/resources/static/scripts/app.js, spring-petclinic-api-gateway/src/main/resources/static/scripts/fragments/nav.html, spring-petclinic-api-gateway/src/main/resources/static/scripts/fragments/welcome.html, spring-petclinic-api-gateway/src/main/resources/static/scripts/infrastructure/httpErrorHandlingInterceptor.js, spring-petclinic-customers-service/src/main/java/org/springframework/samples/petclinic/customers/web/OwnerResource.java
NA
This PR implements AWS CloudWatch RUM integration for the Spring Petclinic application to enable client-side monitoring. The implementation includes:
1. Creating a new CloudWatch RUM stack
2. Adding RUM client integration to the Spring Boot API Gateway
3. Creating RUM-specific canaries for testing
4. Passing RUM configuration from CDK to the application
5. Adding error handling and monitoring in the frontend
*Testing:*
- Deployed the changes to a personal account to verify the functionality.
- Pulse - client pages
- RUM console
- Synthetic canaries
=> feat: Add real user monitoring to EKS demoApp

dotnet-petclinic-payment/PetClinic.PaymentService/PetClinic.PaymentService.csproj, dotnet-petclinic-payment/PetClinic.PaymentService/PetClinicContext.cs, dotnet-petclinic-payment/PetClinic.PaymentService/Program.cs, pet_clinic_insurance_service/Dockerfile, pet_clinic_insurance_service/service/rest.py, spring-petclinic-api-gateway/src/main/java/org/springframework/samples/petclinic/api/application/CustomersServiceClient.java, spring-petclinic-api-gateway/src/main/java/org/springframework/samples/petclinic/api/application/InsuranceServiceClient.java, spring-petclinic-api-gateway/src/main/java/org/springframework/samples/petclinic/api/application/NutritionServiceClient.java, spring-petclinic-api-gateway/src/main/java/org/springframework/samples/petclinic/api/application/PaymentClient.java, spring-petclinic-api-gateway/src/main/java/org/springframework/samples/petclinic/api/application/VisitsServiceClient.java, spring-petclinic-api-gateway/src/main/java/org/springframework/samples/petclinic/api/boundary/web/ApiController.java, spring-petclinic-api-gateway/src/main/java/org/springframework/samples/petclinic/api/boundary/web/ApiGatewayController.java, spring-petclinic-api-gateway/src/main/java/org/springframework/samples/petclinic/api/utils/WellKnownAttributes.java, spring-petclinic-customers-service/src/main/java/org/springframework/samples/petclinic/customers/Config.java, spring-petclinic-customers-service/src/main/java/org/springframework/samples/petclinic/customers/Util.java, spring-petclinic-customers-service/src/main/java/org/springframework/samples/petclinic/customers/web/OwnerResource.java, spring-petclinic-customers-service/src/main/java/org/springframework/samples/petclinic/customers/web/PetResource.java, spring-petclinic-customers-service/src/main/resources/db/hsqldb/data.sql, spring-petclinic-customers-service/src/main/resources/db/mysql/data.sql, spring-petclinic-visits-service/src/main/java/org/springframework/samples/petclinic/visits/Util.java, spring-petclinic-visits-service/src/main/java/org/springframework/samples/petclinic/visits/web/VisitResource.java
Add owner.id as span attributes to multiple services
=> add owner.id as span attribute to multiple services

cdk/ecs/lib/stacks/ecsStack.ts
We intend to publish all pet clinic micro-services to the private ECR. This commit fixes the ECR link for traffic generator.
=> fix: use private ECR for traffic generator

spring-petclinic-visits-service/src/main/java/org/springframework/samples/petclinic/visits/web/VisitResource.java
Add internal spans for visit service
=> Add internal spans for visit service

cdk/eks/lib/stacks/slo-stack.ts
We need to specify the type for exclusion windows. Otherwise, CDK will get confused and cause deployment failure. 
=> fix slo deployment failure

ai-validator/README.md, ai-validator/cdk/.gitignore, ai-validator/cdk/Dockerfile, ai-validator/cdk/README.md, ai-validator/cdk/cdk.json, ai-validator/cdk/ecs.ts, ai-validator/cdk/package-lock.json, ai-validator/cdk/package.json, ai-validator/cdk/tsconfig.json
This PR adds CDK code to deploy the ai-validator tests to ECS.
- **ecs.ts**: Contains CDK code to deploy to ECS
- **Dockerfile**: Defines container image to run ai-validator tests in ECS
=> feat: added CDK code to deploy ai-validator

ai-validator/README.md, ai-validator/cdk/ecs.ts
Change `.env` path for ai-validation tests
=> fix: updated .env path

cdk/eks/lib/manifests/sample-app/nutrition-service-deployment.yaml, data_test/test_cases/traces_test_cases.json
- fixed the filters in trace test
- increase replica to 2 for nutrition service for better availability
=> small improvements
